name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: letsbuildawiki/.github/.github/workflows/site-from-template.yaml@bdf996c3d419c758c9c42e3b4faa3b8c9fd1390c # v2.0.0
